### ISSUE TITLE
B-Pictures Pattern property not being applied correctly

### ISSUE THREAD

**Issue by razorlikes** [Xaymar/OBS-AMD-Advanced-Media-Framework#186]
Hey Xaymar,
It seems like the setting for B-Frames is not getting applied properly.

> 21:38:33.637: [AMF Encoder] [21:38:33.538][VCEEncoderTrace]     Info: SetProperty BPicturesPattern:255
> 21:38:33.637: [AMF Encoder] [21:38:33.538][VCEEncoderTrace]  Warning: SetProperty BPicturesPattern failed in AMFPropertyStorageExImpl with return code:0x5

In my recordings I get the old known VCE 2.0 B-Frame bug again since I updated my driver and the plugin yesterday. Even when I did the recording with just the bare Twitch preset and not a single changed setting.
I also did a fresh driver install with DDU.

Here are log and video file as usual:
Log: [2017-01-11 21-38-24.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/700012/2017-01-11.21-38-24.txt)
Video: http://5.230.156.11/nextcloud/index.php/s/K3NhIpLJSMbxcSz (Just a still image but it happens ingame as well.)

Hardware:
AMD FX8350
AMD Radeon R9 390 Nitro
ASUS Crosshair IV Formula
Corsair XMS3 DDR3 12GB
SSD for OS, HDDs for recording and games.

Software:
OBS version 17.0.0
Plugin version 1.4.3.6
Driver version 16.12.2

**Comment by Xaymar** [comment]
Try with this version: http://cdn.xaymar.com/private/2017/01/11/21/AMD-Encoder-for-OBS-Studio.1.4.3.6.exe

**Comment by razorlikes** [comment]
The issue persists. Here are new log and video files.

Log: [2017-01-11 22-06-30.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/700039/2017-01-11.22-06-30.txt)
Video: http://5.230.156.11/nextcloud/index.php/s/evDWTLG5ELpvHwz

**Comment by Xaymar** [comment]
Welp, let's try it with a memory aligned value - maybe it won't have so much trouble converting that: http://cdn.xaymar.com/private/2017/01/11/22/AMD-Encoder-for-OBS-Studio.1.4.3.7.exe

Once again, try it and if it doesn't work upload a log file with debug checked.

**Comment by razorlikes** [comment]
Didn't fix it either. Aren't AMDs changes to AMF documented somewhere?

Log: [2017-01-11 22-22-58.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/700077/2017-01-11.22-22-58.txt)

**Comment by Xaymar** [comment]
I don't think it's a problem on AMDs side, it's something the Visual Studio compiler does on my end. I don't exactly understand why it does it though. If you can, it would be great if you could try it with this version: http://cdn.xaymar.com/private/2017/01/11/22/AMD-Encoder-for-OBS-Studio.1.4.3.7.exe .

**Comment by razorlikes** [comment]
Still not fixed: [2017-01-11 22-43-19.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/700118/2017-01-11.22-43-19.txt)

**Comment by acp2** [comment]
Updated myself to 1.4.3.6 and then your latest 1.4.3.7 , same is happening.
Here's a log : https://gist.github.com/anonymous/bc0c29210c804f3958793564d7b0f374

**Comment by Xaymar** [comment]
Odd, this sounds like a conversion issue, but I don't understand why. I may have to put in my R9 285 again to understand why, even if it will hurt my PSU :(

**Comment by Xaymar** [comment]
This bug was introduced by commit 9fc4f34e6f8df64cedef59df28fe3193e483334e and fixed in 1.4.3.7. It should work properly again now, at least in my tests it did.

**Comment by acp2** [comment]
Updated to 1.4.3.7 Hotfix 1 , still not fixed for me.
Log - https://gist.github.com/anonymous/62edb316ebfa7225911beb01c19f9d0a
Recording - http://s.go.ro/n4yzv3ug
Do you want me to submit a new issue or can I keep posting here?

**Comment by Xaymar** [comment]
@acp2 You can keep posting here, however I'm no longer able to reproduce the problem. Make absolutely sure that you removed any traces of the builds i linked above (use the uninstaller for example) and then install 1.4.3.7 again.

**Comment by razorlikes** [comment]
Xaymar do you even sleep?

I'm gonna try out the new build when I get home today.

**Comment by Xaymar** [comment]
> Xaymar do you even sleep?

I haven't heard that word in years. I don't even remember what it means...

**Comment by acp2** [comment]
I uninstalled OBS completely , reinstalled it and removed the plugin included with OBS then reinstalled your hotfix.

**Comment by Xaymar** [comment]
I'm not sure why that happens for you then. I was able to reproduce it with the pre-1.4.3.7 hotfix one, but not with the actual hotfix.

**Comment by acp2** [comment]
What else can I do for testing?

**Comment by Xaymar** [comment]
Try to run obs in a portable setup (--portable) using an extracted zip and install the new version on that one. If it works, then something is odd either with Github, your ISP or the browser you used to download.

**Comment by acp2** [comment]
So I downloaded the OBS archive and your plugin via a bridged connection from my phone (completely different provider from my home ISP) with a different browser (Firefox with no extensions) and on a different drive and removed the plugin files , then copied the latest ones.
Same thing is happening with OBS running in portable mode.
Here's the log with debug on - https://gist.github.com/888f0742d2607ca1e07d54ddcc3fc69f
Video - http://s.go.ro/zb44qwn5

**Comment by Xaymar** [comment]
What does your recordEncoder.json say for the profile?

**Comment by acp2** [comment]
Where do I find that?

**Comment by Xaymar** [comment]
If you used a portable install, it's in "config\obs-studio\basic\profiles\\\<profile name>", for static installs it's in "%APPDATA%\obs-studio\basic\profiles\\\<profile name>".

**Comment by acp2** [comment]
http://pastebin.com/EfnLcDbF

**Comment by Xaymar** [comment]
`    "AMF.H264.BFrame.Pattern": -1,`

And there's what's causing the issue for you. Drag the slider once and it should be fixed.

**Comment by acp2** [comment]
That fixed it.

**Comment by razorlikes** [comment]
Wouldn't that mean the plugin built the settings file with a wrong setting in the first place?

**Comment by Xaymar** [comment]
No, the plugin doesn't build settings files. It provides a UI definition, in which there is a slider which goes from 0 to 3. How any of you managed to get a -1 from that is beyond me.

**Comment by acp2** [comment]
I got a -1 on a clean OBS install by just selecting the Twitch profile.

**Comment by Xaymar** [comment]
I don't want to say that it would have been great to have this info from the start, but it would have been great to have this info from the start. I managed to find the actual cause for why it happens and have fixed it now.

**Comment by razorlikes** [comment]
Sorry for the late update, didn't get to test the fix yesterday.

That said, everything works fine now. Although I think I actually had moved the B-Frame slider to three and back to zero when I did my initital testing...
