### ISSUE TITLE
H264/AVC Encoder (AMD Advanced Media Framework) Driver Causes Videos To Be Choppy

### ISSUE THREAD

**Issue by Thenu1200** [Xaymar/OBS-AMD-Advanced-Media-Framework#261]
Hi, I've used the same OBS settings for awhile now and it worked really great! But My Encoder was missing later on, i ended up finding out that i needed to update my amd radeon drivers, so when I did it came back (yay) but the downside was that my videos were now choppy for some reason, even though i used the same settings i have used from before. I also don't want to use x264 because the video Quality is pretty bad and i would prefer using My AMD encoder.

Full System Specifications:
Operating System
	Windows 10 Home 64-bit
CPU
	AMD FX-8370E	38 °C
	Vishera 32nm Technology
RAM
	12.0GB Dual-Channel DDR3 @ 802MHz (11-11-11-28)
Motherboard
	ASUSTeK COMPUTER INC. M52BC_M32BC (Socket 942)	42 °C
Graphics
	ACER X233H (1920x1080@60Hz)
	ACER X233H (1920x1080@59Hz)
	2048MB ATI AMD Radeon R9 255 (ASUStek Computer Inc)	65 °C
Storage
	1863GB TOSHIBA DT01ACA200 (SATA)	37 °C
Optical Drives
	ASUS DVD RAM GHC1N
Audio
	Realtek High Definition Audio

OBS Studio version 19.0.3

Radeon Software version 17.7.1

My Log File: https://gist.github.com/9d2e0aa7cf045c8c79cfb18448d348ec

**Comment by Xaymar** [comment]
1. Did you upgrade from OBS 18.x to 19.x?
2. Did you upgrade the plugin from 1.4.x to 2.x? (Automatically yes if you just upgraded to 19.x)
3. Did you actually read through the last step of the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting)? Your log is missing critical debug information - please follow the guide and also check the "Debug" checkbox in the settings.

Reason i ask all of this is that 2.x is a full rewrite from scratch, it made the code base much easier to write for (allowing quicker support and updates, if there need to be updates) and actually fixed many of the outstanding issues which i previously merely added workarounds for. If a configuration that worked in 1.4.x no longer works correctly in 2.x it's because the properties no longer exist.

**Comment by Thenu1200** [comment]
Sorry, I didnt read that part. But I fixed It now. And yes i upgraded from 18.x to 19.x

**Comment by Xaymar** [comment]
Still missing a log with OBS started using "--verbose --unfiltered_log". Just add this to the shortcut to OBS: 
![image](https://user-images.githubusercontent.com/437395/28381522-7899dd5e-6cbb-11e7-955c-569cdd5aca81.png)

This will currently only work on 64-bit OBS as there is an unfixed driver bug that crashes the debug routines in 32-bit.

**Comment by Thenu1200** [comment]
do i have to add a space In between?

**Comment by Xaymar** [comment]
Yes

**Comment by Thenu1200** [comment]
ok, so now do i have to send u the log? If so, here: https://gist.github.com/2c6397e10f37536addb474157a63b2e1

**Comment by Thenu1200** [comment]
Now What?

**Comment by Thenu1200** [comment]
https://gist.github.com/3d99ba596c95442b36320a9a68de717e 

this is the log

**Comment by Xaymar** [comment]
Wait until I have read through the log.

**Comment by Thenu1200** [comment]
oh, sorry I thought u were done 😅

**Comment by Xaymar** [comment]
```
13:53:42.548: 	Adapter 1: AMD Radeon (TM) R9 255
13:53:42.548: 	  Dedicated VRAM: 2127716352
13:53:42.548: 	  Shared VRAM:    2103138304
13:53:42.548: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
13:53:42.548: 	  output 2: pos={1920, 0}, size={1920, 1080}, attached=true
13:53:43.669: [AMF] Version 2.1.6 loaded (Compiled: 1.4.2.0, Runtime: 1.4.2.0, Library: 1;4;2;0;17.10.3211.1031;201707041820;CL#1429932).
```

GPU is unknown to me, but seems to be a lower powered R9 260, so I'll use that GPU for reference. Version and Runtime looks good.

```

```


```
13:53:57.032: [AMF] [H264]<Id: 7> Encoder Parameters:
13:53:57.032: [AMF] [H264]<Id: 7>   Backend:
13:53:57.033: [AMF] [H264]<Id: 7>     Video API: Direct3D 11
13:53:57.033: [AMF] [H264]<Id: 7>     Video Adapter: AMD Radeon (TM) R9 255 (VEN_1002/DEV_6835/SUB_86201043/REV_0000)
13:53:57.033: [AMF] [H264]<Id: 7>     OpenCL: Not Supported
13:53:57.033: [AMF] [H264]<Id: 7>       Transfer: Disabled
13:53:57.033: [AMF] [H264]<Id: 7>       Conversion: Disabled
13:53:57.034: [AMF] [H264]<Id: 7>     Multi-Threading: Disabled
13:53:57.034: [AMF] [H264]<Id: 7>     Queue Size: 4
13:53:57.034: [AMF] [H264]<Id: 7>   Frame:
13:53:57.034: [AMF] [H264]<Id: 7>     Format: NV12 601 Partial
13:53:57.034: [AMF] [H264]<Id: 7>     Resolution: 1920x1080
13:53:57.034: [AMF] [H264]<Id: 7>     Frame Rate: 60/1
13:53:57.034: [AMF] [H264]<Id: 7>     Aspect Ratio: 1:1
13:53:57.035: [AMF] [H264]<Id: 7>   Static:
13:53:57.035: [AMF] [H264]<Id: 7>     Usage: Transcoding
13:53:57.035: [AMF] [H264]<Id: 7>     Quality Preset: Balanced
13:53:57.035: [AMF] [H264]<Id: 7>     Profile: Main 4.2
13:53:57.035: [AMF] [H264]<Id: 7>     Coding Type: Automatic
13:53:57.035: [AMF] [H264]<Id: 7>     Max. Reference Frames: 4
13:53:57.035: [AMF] [H264]<Id: 7>     Max. Long-Term Reference Frames: 0
13:53:57.036: [AMF] [H264]<Id: 7>   Rate Control:
13:53:57.036: [AMF] [H264]<Id: 7>     Method: Constant Quantization Parameter
13:53:57.036: [AMF] [H264]<Id: 7>     Pre-Pass Mode: Disabled
13:53:57.036: [AMF] [H264]<Id: 7>     QP:
13:53:57.037: [AMF] [H264]<Id: 7>       Range: 18 - 51
13:53:57.037: [AMF] [H264]<Id: 7>       I-Frame: 19
13:53:57.037: [AMF] [H264]<Id: 7>       P-Frame: 21
13:53:57.037: [AMF] [H264]<Id: 7>       B-Frame: 22
13:53:57.037: [AMF] [H264]<Id: 7>     Bitrate:
13:53:57.037: [AMF] [H264]<Id: 7>       Target: 20000000 bit/s
13:53:57.038: [AMF] [H264]<Id: 7>       Peak: 20000000 bit/s
13:53:57.038: [AMF] [H264]<Id: 7>     Flags:
13:53:57.038: [AMF] [H264]<Id: 7>       Filler Data: Enabled
13:53:57.038: [AMF] [H264]<Id: 7>       Frame Skipping: Disabled
13:53:57.038: [AMF] [H264]<Id: 7>         Period: 0 Frames
13:53:57.038: [AMF] [H264]<Id: 7>         Behaviour: Skip every Nth frame
13:53:57.038: [AMF] [H264]<Id: 7>       Variance Based Adaptive Quantization: Enabled
13:53:57.039: [AMF] [H264]<Id: 7>       Enforce Hypothetical Reference Decoder: Enabled
13:53:57.039: [AMF] [H264]<Id: 7>     Video Buffering Verfier:
13:53:57.039: [AMF] [H264]<Id: 7>       Buffer Size: 50000000 bits
13:53:57.039: [AMF] [H264]<Id: 7>       Initial Fullness: 100 %
13:53:57.039: [AMF] [H264]<Id: 7>     Max. Access Unit Size: 0
13:53:57.039: [AMF] [H264]<Id: 7>   Picture Control:
13:53:57.040: [AMF] [H264]<Id: 7>     Period:
13:53:57.040: [AMF] [H264]<Id: 7>       IDR: 120 Frames
13:53:57.040: [AMF] [H264]<Id: 7>       I: 0 Frames
13:53:57.040: [AMF] [H264]<Id: 7>       P: 0 Frames
13:53:57.040: [AMF] [H264]<Id: 7>       B: 0 Frames
13:53:57.040: [AMF] [H264]<Id: 7>     Header Insertion Spacing: 0
13:53:57.041: [AMF] [H264]<Id: 7>     GOP Alignment: Enabled
13:53:57.041: [AMF] [H264]<Id: 7>     Deblocking Filter: Enabled
13:53:57.041: [AMF] [H264]<Id: 7>     Motion Estimation: Quarter, Half
13:53:57.041: [AMF] [H264]<Id: 7>     B-Frames:
13:53:57.041: [AMF] [H264]<Id: 7>       Pattern: 0
13:53:57.041: [AMF] [H264]<Id: 7>       Delta QP: N/A
13:53:57.042: [AMF] [H264]<Id: 7>       Reference: Disabled
13:53:57.042: [AMF] [H264]<Id: 7>       Reference Delta QP: N/A
13:53:57.042: [AMF] [H264]<Id: 7>   Intra-Refresh:
13:53:57.042: [AMF] [H264]<Id: 7>     Number of Macroblocks Per Slot: 0
13:53:57.042: [AMF] [H264]<Id: 7>     Number of Stripes: 2147483647
13:53:57.042: [AMF] [H264]<Id: 7>   Slicing:
13:53:57.043: [AMF] [H264]<Id: 7>     Mode: 140725195441980
13:53:57.043: [AMF] [H264]<Id: 7>     Slices Per Frame: 1
13:53:57.043: [AMF] [H264]<Id: 7>     Control Mode: Unknown 0
13:53:57.043: [AMF] [H264]<Id: 7>     Control Size: 0
13:53:57.043: [AMF] [H264]<Id: 7>     Maximum Slice Size: 2147483647
13:53:57.043: [AMF] [H264]<Id: 7>   Experimental:
13:53:57.044: [AMF] [H264]<Id: 7>     Low Latency: Disabled
13:53:57.044: [AMF] [H264]<Id: 7>     Ultra Low Latency: Disabled
```

Profile should be High for 1080p60, otherwise okay. Keyframe Interval of 2 might be too low, consider using 4 or 5 with CQP. VBAQ is enabled, but hopefully does not have an effect - if the option is available to you, try turning it off.

```
13:53:57.201: [AMF] <Id: 7> Initial Frame Latency is 62008500 nanoseconds.
13:53:57.201: [AMF] <Id: 7>    Timings: Allocate(       0 ns) Store(10529500 ns) Convert(  499800 ns) Main(62008500 ns) Load(       0 ns)
13:53:57.217: [AMF] <Id: 7>    Timings: Allocate(       0 ns) Store( 5000500 ns) Convert(       0 ns) Main(66513600 ns) Load(       0 ns)
13:53:57.703: [AMF] <Id: 7>    Timings: Allocate(       0 ns) Store( 4999900 ns) Convert(       0 ns) Main(519026100 ns) Load(       0 ns)
13:53:57.735: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
13:53:57.736: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
13:53:57.737: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
13:53:57.739: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
13:53:57.740: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
13:53:57.741: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
13:53:57.743: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
```

This is where it gets weird. Even though we have submitted more than enough frames to the GPU encoder, it is stalling quite a bit. This happens multiple times throughout encoding, resulting in the rather huge frame loss you experience.

-----

Try the following:

* Increase Keyframe Interval to 5 seconds.
* Set Profile to High instead of Main.
* Increase Queue Size to any value above 4, might help with stabilization. (Requires View Mode: Expert)
* Increase the Power Limit of the GPU in Wattman.
* Increase the fan curve of the GPU in Wattman.

**Comment by Thenu1200** [comment]
Ok thanks!

**Comment by Thenu1200** [comment]
I cant find profile

**Comment by Thenu1200** [comment]
nm

**Comment by Thenu1200** [comment]
Where do i find wattman

**Comment by Xaymar** [comment]
Wattman is part of AMD Radeon Settings.

**Comment by Thenu1200** [comment]
Is it on obs?

**Comment by Xaymar** [comment]
No that is part of the AMD driver.

**Comment by Thenu1200** [comment]
oh ok

**Comment by Thenu1200** [comment]
is it global overdrive on amd?

**Comment by Xaymar** [comment]
Yes.

**Comment by Thenu1200** [comment]
Is power limit supposed to be power control?

**Comment by Xaymar** [comment]
If you do not know how to use Wattman, skip the steps requiring Wattman.

**Comment by Thenu1200** [comment]
ok

**Comment by Thenu1200** [comment]
It's still really choppy 
https://gist.github.com/66233d4117e080b20402f6a372eda777

**Comment by Xaymar** [comment]
There is not much I can do then. From the log files, you should get about 60 fps. If these identical settings worked in a version before 2.x, you can always install an older plugin version to downgrade again.

**Comment by Thenu1200** [comment]
how do I do that? Do u have a link to an older version?

**Comment by Xaymar** [comment]
What was the last version of OBS it worked with? If it was 18.x, this is the version you want: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/download/1.4.3.11/AMD-Encoder-for-OBS-Studio.1.4.3.11.exe

**Comment by Thenu1200** [comment]
Hi, i downloaded the later version and it works but now it says my encoding is overloaded and when i watch the vid, every now and then the video freezes

**Comment by Thenu1200** [comment]
this is the log: https://gist.github.com/b4d33577778c0e6f2db9587ca956e02d

**Comment by Xaymar** [comment]
Same issue as before, your GPU is still stalling. You might want to ask on the AMD support forums for help on solving this issue.

**Comment by Thenu1200** [comment]
do i just tell AMD my GPU is stalling?

**Comment by Xaymar** [comment]
https://community.amd.com/community/support-forums

**Comment by Xaymar** [comment]
Also, something to try out for you: Do a clean install of your GPU Driver! Sometimes there are stale copies left around, so a clean install may help.

**Comment by Thenu1200** [comment]
But wont a clean install get rid of all my files?
and i was thinking of doing that from the beginning

**Comment by Xaymar** [comment]
By clean install I mean use the "Clean Install" or "Full Reinstall" button that AMD drivers offer when installing, not reinstalling your OS.

**Comment by Thenu1200** [comment]
Oh ok thanks, I was really confused and didnt want to take the risk of possibly losing all my files.

**Comment by Thenu1200** [comment]
Ok, welp the clean install didnt seem to help because it still says encoding is overloaded and the videos still turn out choppy. I havent really gotten a reply yet from the AMD support center so I really dont know how to fix it.
This is my log after I clean installed: 
https://gist.github.com/777f8853b1bc45ee5aa2eaf57318bfa6

**Comment by Thenu1200** [comment]
Wait, nm I think i found the fix, i put my keyframe interval to 4 instead of 1 (which it was set to) and its working great, Btw what does key frame interval actually do?

**Comment by Xaymar** [comment]
Keyframe Interval is how often it generates full size frames (pretty much uncompressed). Those require a lot of time to transfer, which is why that is normally set to more than 2 seconds for any system.

**Comment by max20091** [comment]
Did you OCed your GPU? I think that cause this stupid issue so revert your GPU to original clock, I just have same issue like you.
You just need to test with a black scene and check if encoder is overloaded, doing other things like play games may make the result goes wrong.
This is GCN 1 GPU problem :(

**Comment by Xaymar** [comment]
Closed due to inactivity.
